/**
 * Predefined autocomplete suggestions for the artist profile screen.
 * Free text is also allowed — these power suggestions and quick-picks.
 * Mirrors Mitro.Artist.UI/src/services/profileSuggestions.ts.
 */

export const MAX_SKILLS = 10;
export const MAX_LANGUAGES = 5;
export const MAX_CATEGORIES = 5;
export const MAX_SUBCATEGORIES_PER_CATEGORY = 10;

export const SKILL_SUGGESTIONS: string[] = [
  'Singing',
  'Guitar',
  'Piano',
  'Keyboard',
  'Drums',
  'Violin',
  'Flute',
  'Ukulele',
  'Beatboxing',
  'Rap',
  'Songwriting',
  'DJing',
  'Music Production',
  'Classical Music',
  'Bollywood Songs',
  'Ghazal',
  'Devotional Music',
  'Dance',
  'Hip Hop Dance',
  'Classical Dance',
  'Bharatanatyam',
  'Kathak',
  'Contemporary Dance',
  'Freestyle Dance',
  'Comedy',
  'Stand-up Comedy',
  'Mimicry',
  'Storytelling',
  'Poetry',
  'Shayari',
  'Acting',
  'Voice Over',
  'Mimicry & Voices',
  'Fitness',
  'Yoga',
  'Zumba',
  'Aerobics',
  'Martial Arts',
  'Meditation',
  'Mental Wellness',
  'Life Coaching',
  'Astrology',
  'Tarot Reading',
  'Numerology',
  'Palmistry',
  'Vastu',
  'Horoscope',
  'Art & Craft',
  'Painting',
  'Sketching',
  'Calligraphy',
  'Digital Art',
  'Makeup',
  'Hairstyling',
  'Fashion Styling',
  'Cooking',
  'Baking',
  'Cocktail Making',
  'Food Styling',
  'Gaming',
  'ESports',
  'Live Commentary',
  'Tech Reviews',
  'Photography',
  'Videography',
  'Magic Tricks',
  'Puppetry',
];

export const LANGUAGE_SUGGESTIONS: string[] = [
  'English',
  'Hindi',
  'Bengali',
  'Telugu',
  'Marathi',
  'Tamil',
  'Urdu',
  'Gujarati',
  'Kannada',
  'Odia',
  'Malayalam',
  'Punjabi',
  'Assamese',
  'Maithili',
  'Bhojpuri',
  'Sanskrit',
  'Spanish',
  'French',
  'German',
  'Arabic',
  'Mandarin',
  'Japanese',
  'Korean',
  'Russian',
  'Portuguese',
];
