const fs = require('fs');
const path = require('path');
const {
  withAndroidManifest,
  withDangerousMod,
  withMainApplication,
} = require('@expo/config-plugins');

/**
 * Incoming private-call ringing (Android).
 *
 * `android/` is generated by `expo prebuild` and gitignored, so everything the
 * feature needs natively lives in plugins/incoming-call/*.kt and is applied here:
 *   1. copies the Kotlin sources into android/app/src/main/java/<package>/
 *   2. manifest: USE_FULL_SCREEN_INTENT + WAKE_LOCK, the messaging service
 *      (priority 100 so it wins over React Native Firebase's own service - ours
 *      extends it, so all other pushes keep working), the decline receiver, the
 *      headless decline service and the lock-screen call activity
 *   3. registers IncomingCallPackage (JS bridge: NativeModules.IncomingCall)
 *
 * Idempotent: safe to run on every prebuild.
 */
const ANDROID_PACKAGE = 'com.mitro.artist';
const SOURCE_DIR = 'plugins/incoming-call';
const KOTLIN_FILES = [
  'IncomingCallNotifier.kt',
  'IncomingCallMessagingService.kt',
  'IncomingCallActionReceiver.kt',
  'IncomingCallHeadlessService.kt',
  'IncomingCallActivity.kt',
  'IncomingCallModule.kt',
];

const addPermission = (manifest, name) => {
  manifest['uses-permission'] = manifest['uses-permission'] || [];
  if (!manifest['uses-permission'].some((p) => p.$['android:name'] === name)) {
    manifest['uses-permission'].push({ $: { 'android:name': name } });
  }
};

const upsert = (list, name, entry) => {
  const i = list.findIndex((item) => item.$['android:name'] === name);
  if (i >= 0) list[i] = entry;
  else list.push(entry);
};

const withManifest = (config) =>
  withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    addPermission(manifest, 'android.permission.USE_FULL_SCREEN_INTENT');
    addPermission(manifest, 'android.permission.WAKE_LOCK');
    addPermission(manifest, 'android.permission.VIBRATE');

    const app = manifest.application?.[0];
    if (!app) return cfg;
    app.service = app.service || [];
    app.receiver = app.receiver || [];
    app.activity = app.activity || [];

    upsert(app.service, '.IncomingCallMessagingService', {
      $: { 'android:name': '.IncomingCallMessagingService', 'android:exported': 'false' },
      'intent-filter': [
        {
          $: { 'android:priority': '100' },
          action: [{ $: { 'android:name': 'com.google.firebase.MESSAGING_EVENT' } }],
        },
      ],
    });

    upsert(app.service, '.IncomingCallHeadlessService', {
      $: { 'android:name': '.IncomingCallHeadlessService', 'android:exported': 'false' },
    });

    upsert(app.receiver, '.IncomingCallActionReceiver', {
      $: { 'android:name': '.IncomingCallActionReceiver', 'android:exported': 'false' },
    });

    upsert(app.activity, '.IncomingCallActivity', {
      $: {
        'android:name': '.IncomingCallActivity',
        'android:exported': 'false',
        'android:showWhenLocked': 'true',
        'android:turnScreenOn': 'true',
        'android:launchMode': 'singleTask',
        'android:taskAffinity': '',
        'android:excludeFromRecents': 'true',
        'android:screenOrientation': 'portrait',
        'android:theme': '@android:style/Theme.DeviceDefault.NoActionBar',
      },
    });

    return cfg;
  });

const withKotlinSources = (config) =>
  withDangerousMod(config, [
    'android',
    async (cfg) => {
      const from = path.join(cfg.modRequest.projectRoot, SOURCE_DIR);
      const to = path.join(
        cfg.modRequest.platformProjectRoot,
        'app/src/main/java',
        ...ANDROID_PACKAGE.split('.'),
      );
      fs.mkdirSync(to, { recursive: true });
      for (const file of KOTLIN_FILES) {
        fs.copyFileSync(path.join(from, file), path.join(to, file));
      }
      return cfg;
    },
  ]);

const withPackageRegistration = (config) =>
  withMainApplication(config, (cfg) => {
    let src = cfg.modResults.contents;
    if (src.includes('IncomingCallPackage')) return cfg;

    const marker = '// add(MyReactNativePackage())';
    if (src.includes(marker)) {
      src = src.replace(marker, `${marker}\n              add(IncomingCallPackage())`);
    } else {
      const applyRe = /(PackageList\(this\)\.packages\.apply \{)/;
      if (!applyRe.test(src)) {
        throw new Error('withIncomingCallNotification: could not find PackageList in MainApplication');
      }
      src = src.replace(applyRe, '$1\n              add(IncomingCallPackage())');
    }
    cfg.modResults.contents = src;
    return cfg;
  });

module.exports = function withIncomingCallNotification(config) {
  config = withManifest(config);
  config = withKotlinSources(config);
  config = withPackageRegistration(config);
  return config;
};
